-- MySQL Script generated by MySQL Workbench
-- 11/08/16 17:21:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema summer_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema summer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `summer_db` DEFAULT CHARACTER SET utf8 ;
USE `summer_db` ;

-- -----------------------------------------------------
-- Table `summer_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summer_db`.`usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil` INT NULL,
  `statusAtividade` INT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuarios` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summer_db`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summer_db`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NULL,
  `numero` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `uf` VARCHAR(255) NULL,
  `cidade` VARCHAR(255) NULL,
  `cep` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summer_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summer_db`.`clientes` (
  `cpf` VARCHAR(255) NOT NULL,
  `endereco_id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `dataCadastro` DATETIME NOT NULL,
  `rg` VARCHAR(255) NULL,
  `telFixo` VARCHAR(255) NULL,
  `telCelular` VARCHAR(255) NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_clientes_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_clientes_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `summer_db`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summer_db`.`os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summer_db`.`os` (
  `idOs` INT NOT NULL AUTO_INCREMENT,
  `dataEmissao` DATETIME NULL,
  `dataPrevEntrega` DATETIME NULL,
  `longEixoOd` DECIMAL(10,3) NULL,
  `longEsfOd` DECIMAL(10,3) NULL,
  `longEixoOe` DECIMAL(10,3) NULL,
  `longAlturaOe` DECIMAL(10,3) NULL,
  `longDnpOe` DECIMAL(10,3) NULL,
  `longCilOe` DECIMAL(10,3) NULL,
  `longCilOd` DECIMAL(10,3) NULL,
  `longAlturaOd` DECIMAL(10,3) NULL,
  `longEsfOe` DECIMAL(10,3) NULL,
  `perCilOe` DECIMAL(10,3) NULL,
  `perEixoOd` DECIMAL(10,3) NULL,
  `perEsfOe` DECIMAL(10,3) NULL,
  `perCilOd` DECIMAL(10,3) NULL,
  `perEixoOe` DECIMAL(10,3) NULL,
  `perDnpOd` DECIMAL(10,3) NULL,
  `lentes` VARCHAR(255) NULL,
  `valor` DECIMAL(10,3) NULL,
  `medico` VARCHAR(255) NULL,
  `adicao` DECIMAL(10,3) NULL,
  `perAlturaOe` DECIMAL(10,3) NULL,
  `perAlturaOd` DECIMAL(10,3) NULL,
  `receita` VARCHAR(255) NULL,
  `dataVencLentes` DATETIME NULL,
  `perEsfOd` DECIMAL(10,3) NULL,
  `armacao` VARCHAR(255) NULL,
  `observacao` TEXT NULL,
  `longDnpOd` DECIMAL(10,3) NULL,
  `statusPg` TINYINT(1) NULL,
  `formaPg` INT NULL,
  `dataPg` DATETIME NULL,
  `nParcelas` INT NULL,
  `clientes_cpf` VARCHAR(255) NOT NULL,
  INDEX `fk_os_clientes1_idx` (`clientes_cpf` ASC),
  PRIMARY KEY (`idOs`),
  CONSTRAINT `fk_os_clientes1`
    FOREIGN KEY (`clientes_cpf`)
    REFERENCES `summer_db`.`clientes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summer_db`.`os_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summer_db`.`os_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `os_idos` INT NULL,
  `usuarios_idUsuarios` INT NULL,
  `statusAndamentoOs` INT NULL,
  `dataStatusAndamentoOs` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_os_has_usuarios_usuarios1_idx` (`usuarios_idUsuarios` ASC),
  INDEX `fk_os_has_usuarios_os1_idx` (`os_idos` ASC),
  CONSTRAINT `fk_os_has_usuarios_os1`
    FOREIGN KEY (`os_idos`)
    REFERENCES `summer_db`.`os` (`idOs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_idUsuarios`)
    REFERENCES `summer_db`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
